app:
  name: "ginapp"
  env: "prod"
  port: 3000
  version: "1.0.0"

dynamo:
  region: "us-west-1"
  post_table_name: "YQ_POST_TABLE"
  book_table_name: "YQ_BOOK_TABLE"

log:
  level: "debug"
  filename: "./logs/blog.log"
  maxsize: 1
  maxbackups: 5
  maxage: 30
